### ISSUE TITLE
Main window fails to open on Mac

### ISSUE THREAD

**Issue by Fhoughton** [dotStart/Beacon#18]
OSX Beacon halts at 'Hiding tray icon' stage, right before window open.  

**Reproduction Steps**
Describe the steps to reproduce the behavior:
1. Install the JDK
2. Download Beacon v3.0.0 Alpha 2
3. Execute it from terminal via 'java -jar Beacon.jar'
4. Wait and let it execute to the splash
5. The load bar should finish and the console should reach minimizing tray icon but the main window should never open and the splash stays

**Expected Behavior**
'Switched to main window' and window opens

**Log files**
https://pastebin.com/NHY8eyNM

**Environment (please complete the following information):**
 - OS: MacOS
 - Application Version: 3.0.0-alpha.2

**Additional Context**
Error has occurred on two separate machines.

**Comment by dotStart** [comment]
This issue seems be caused by the deadlock issue fixed with [v3.0.0-alpha.3](https://github.com/dotStart/Beacon/releases/tag/v3.0.0-alpha.3) (which is now available from the Releases section). Please try again on that version and reopen the issue if it persists.

**Comment by Fhoughton** [comment]
@dotStart Just got my friend to try it on their mac, apparently it still hangs at the exact same point even on alpha 3. It doesn't hang on my Linux machine so it's somehow platform dependent (unless it's due to me using OpenJDK but I doubt that's the case).
